# EDA (Exploratory Data Analysis)

In [1]:
import os

import numpy
import pandas as pd
import pandas_profiling

os.environ['QT_QPA_PLATFORM'] = 'offscreen'

In [2]:
# Load raw data from file.
data_frame_raw = pd.read_csv(r"./data/census.csv")

In [14]:
# Load cleaned data from file.
data_frame = pd.read_csv(r"./data/census-clean.csv")

In [15]:
print("DataFrame head (1st 5 rows):")
data_frame.head()

DataFrame head (1st 5 rows):


age         workclass   fnlgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country salary  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

In [38]:
data_frame.shape

(32561, 15)

In [17]:
data_frame.columns

Index(['age', 'workclass', 'fnlgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'salary'],
      dtype='object')

In [16]:
data_frame["age"].unique()

array([39, 50, 38, 53, 28, 37, 49, 52, 31, 42, 30, 23, 32, 40, 34, 25, 43, 54, 35, 59, 56, 19, 20, 45, 22, 48, 21, 24, 57, 44, 41, 29, 18, 47, 46, 36, 79, 27, 67, 33, 76, 17, 55, 61, 70, 64, 71, 68, 66, 51, 58, 26, 60, 90, 75, 65, 77, 62, 63, 80, 72, 74, 69, 73, 81, 78, 88, 82, 83, 84, 85, 86, 87])

In [18]:
data_frame["workclass"].unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov', 'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked'], dtype=object)

In [19]:
data_frame["fnlgt"].unique()

array([ 77516,  83311, 215646, ...,  34066,  84661, 257302])

In [20]:
data_frame["education"].unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college', 'Assoc-acdm', 'Assoc-voc', '7th-8th', 'Doctorate', 'Prof-school', '5th-6th', '10th', '1st-4th', 'Preschool', '12th'], dtype=object)

In [21]:
data_frame["education-num"].unique()

array([13,  9,  7, 14,  5, 10, 12, 11,  4, 16, 15,  3,  6,  2,  1,  8])

In [22]:
data_frame["marital-status"].unique()

array(['Never-married', 'Married-civ-spouse', 'Divorced', 'Married-spouse-absent', 'Separated', 'Married-AF-spouse', 'Widowed'], dtype=object)

In [24]:
data_frame["occupation"].unique()

array(['Adm-clerical', 'Exec-managerial', 'Handlers-cleaners', 'Prof-specialty', 'Other-service', 'Sales', 'Craft-repair', 'Transport-moving', 'Farming-fishing', 'Machine-op-inspct', 'Tech-support', '?', 'Protective-serv', 'Armed-Forces', 'Priv-house-serv'], dtype=object)

In [25]:
data_frame["relationship"].unique()

array(['Not-in-family', 'Husband', 'Wife', 'Own-child', 'Unmarried', 'Other-relative'], dtype=object)

In [31]:
data_frame["race"].unique()

array(['White', 'Black', 'Asian-Pac-Islander', 'Amer-Indian-Eskimo', 'Other'], dtype=object)

In [32]:
data_frame["sex"].unique()

array(['Male', 'Female'], dtype=object)

In [26]:
data_frame["capital-gain"].unique()

array([ 2174,     0, 14084,  5178,  5013,  2407, 14344, 15024,  7688, 34095,  4064,  4386,  7298,  1409,  3674,  1055,  3464,  2050,  2176,   594, 20051,  6849,  4101,  1111,  8614,  3411,  2597, 25236,  4650,  9386,  2463,  3103, 10605,  2964,  3325,  2580,  3471,  4865, 99999,  6514,  1471,
        2329,  2105,  2885, 25124, 10520,  2202,  2961, 27828,  6767,  2228,  1506, 13550,  2635,  5556,  4787,  3781,  3137,  3818,  3942,   914,   401,  2829,  2977,  4934,  2062,  2354,  5455, 15020,  1424,  3273, 22040,  4416,  3908, 10566,   991,  4931,  1086,  7430,  6497,   114,  7896,
        2346,  3418,  3432,  2907,  1151,  2414,  2290, 15831, 41310,  4508,  2538,  3456,  6418,  1848,  3887,  5721,  9562,  1455,  2036,  1831, 11678,  2936,  2993,  7443,  6360,  1797,  1173,  4687,  6723,  2009,  6097,  2653,  1639, 18481,  7978,  2387,  5060])

In [27]:
data_frame["capital-loss"].unique()

array([   0, 2042, 1408, 1902, 1573, 1887, 1719, 1762, 1564, 2179, 1816, 1980, 1977, 1876, 1340, 2206, 1741, 1485, 2339, 2415, 1380, 1721, 2051, 2377, 1669, 2352, 1672,  653, 2392, 1504, 2001, 1590, 1651, 1628, 1848, 1740, 2002, 1579, 2258, 1602,  419, 2547, 2174, 2205, 1726, 2444, 1138, 2238,
        625,  213, 1539,  880, 1668, 1092, 1594, 3004, 2231, 1844,  810, 2824, 2559, 2057, 1974,  974, 2149, 1825, 1735, 1258, 2129, 2603, 2282,  323, 4356, 2246, 1617, 1648, 2489, 3770, 1755, 3683, 2267, 2080, 2457,  155, 3900, 2201, 1944, 2467, 2163, 2754, 2472, 1411])

In [30]:
data_frame["hours-per-week"].unique()

array([40, 13, 16, 45, 50, 80, 30, 35, 60, 20, 52, 44, 15, 25, 38, 43, 55, 48, 58, 32, 70,  2, 22, 56, 41, 28, 36, 24, 46, 42, 12, 65,  1, 10, 34, 75, 98, 33, 54,  8,  6, 64, 19, 18, 72,  5,  9, 47, 37, 21, 26, 14,  4, 59,  7, 99, 53, 39, 62, 57, 78, 90, 66, 11, 49, 84,  3, 17, 68, 27, 85, 31, 51,
       77, 63, 23, 87, 88, 73, 89, 97, 94, 29, 96, 67, 82, 86, 91, 81, 76, 92, 61, 74, 95])

In [28]:
data_frame["native-country"].unique()

array(['United-States', 'Cuba', 'Jamaica', 'India', '?', 'Mexico', 'South', 'Puerto-Rico', 'Honduras', 'England', 'Canada', 'Germany', 'Iran', 'Philippines', 'Italy', 'Poland', 'Columbia', 'Cambodia', 'Thailand', 'Ecuador', 'Laos', 'Taiwan', 'Haiti', 'Portugal', 'Dominican-Republic', 'El-Salvador',
       'France', 'Guatemala', 'China', 'Japan', 'Yugoslavia', 'Peru', 'Outlying-US(Guam-USVI-etc)', 'Scotland', 'Trinadad&Tobago', 'Greece', 'Nicaragua', 'Vietnam', 'Hong', 'Ireland', 'Hungary', 'Holand-Netherlands'], dtype=object)

In [33]:
# Slice example.
feature = "age"
feature_value = 39
df = data_frame[data_frame[feature] == feature_value]
df.head()

age    workclass   fnlgt     education  education-num  \
0     39    State-gov   77516     Bachelors             13   
28    39      Private  367260       HS-grad              9   
129   39      Private  365739  Some-college             10   
166   39  Federal-gov  235485    Assoc-acdm             12   
297   39            ?  157443       Masters             14   

         marital-status       occupation   relationship                race  \
0         Never-married     Adm-clerical  Not-in-family               White   
28             Divorced  Exec-managerial  Not-in-family               White   
129            Divorced     Craft-repair  Not-in-family               White   
166       Never-married  Exec-managerial  Not-in-family               White   
297  Married-civ-spouse                ?           Wife  Asian-Pac-Islander   

        sex  capital-gain  capital-loss  hours-per-week native-country salary  
0      Male          2174             0              40  United-States  <=50K  
28     Male             0             0              80  United-States  <=50K  
129    Male             0             0              40  United-States  <=50K  
166    Male             0             0              42  United-States  <=50K  
297  Female          3464             0              40              ?  <=50K

In [35]:
# Slice example.
feature = "native-country"
feature_value = "United-States"
df = data_frame[data_frame[feature] == feature_value]
df.head()

age         workclass   fnlgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
5   37           Private  284582    Masters             14   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
5  Married-civ-spouse    Exec-managerial           Wife  White  Female   

   capital-gain  capital-loss  hours-per-week native-country salary  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
5             0             0              40  United-States  <=50K

In [37]:
df.shape

(29170, 15)

In [39]:
data_frame[feature].value_counts()

United-States                 29170
Mexico                          643
?                               583
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        64
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
France                      